
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import conexion.Conexion;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abrah
 */
public class Inventario extends javax.swing.JFrame {
    DefaultTableModel modelo;
    private Connection con;

    /**
     * Creates new form Hardware
     */
    public Inventario() {
        initComponents();
       setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
       modelo = (DefaultTableModel) jTinve.getModel();
         modelo.setRowCount(0);
         
    // Conectar con la base de datos
    con = Conexion.getConnection();

    // Cargar inventario al iniciar
    cargarInventario();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPMostrar4 = new javax.swing.JPanel();
        jBvolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTbuscar = new javax.swing.JTextField();
        jBeliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTinve = new javax.swing.JTable();
        jBregistrar = new javax.swing.JButton();
        jBactualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jCNombre = new javax.swing.JComboBox<>();
        jTcategoria = new javax.swing.JTextField();
        jTcantidad = new javax.swing.JTextField();
        jTprecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPMostrar4.setBackground(new java.awt.Color(204, 255, 255));

        jBvolver.setBackground(new java.awt.Color(51, 153, 255));
        jBvolver.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jBvolver.setText("Volver");
        jBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel1.setText("Inventario ");

        jTbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbuscarKeyReleased(evt);
            }
        });

        jBeliminar.setBackground(new java.awt.Color(51, 153, 255));
        jBeliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBeliminar.setText("Elliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jTinve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                " Id", "Nombre", "Categoria", "Cantidad", "Precio"
            }
        ));
        jTinve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTinveMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTinve);

        jBregistrar.setBackground(new java.awt.Color(51, 153, 255));
        jBregistrar.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jBregistrar.setText("Registrar");
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });

        jBactualizar.setBackground(new java.awt.Color(51, 153, 255));
        jBactualizar.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jBactualizar.setText("Actualizar");
        jBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel2.setText("BUSCAR:");

        jLabel3.setText("Id:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Categoria:");

        jLabel6.setText("Cantidad:");

        jLabel7.setText("Precio:");

        jCNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jose Antonio Rojas de la Fuente", "Marcos de la Piedra de Bonnie", "Maria Antonieta de las Nieves", "Roxana de los Angeles Cantoral" }));

        javax.swing.GroupLayout jPMostrar4Layout = new javax.swing.GroupLayout(jPMostrar4);
        jPMostrar4.setLayout(jPMostrar4Layout);
        jPMostrar4Layout.setHorizontalGroup(
            jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMostrar4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jBeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPMostrar4Layout.createSequentialGroup()
                .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMostrar4Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMostrar4Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMostrar4Layout.createSequentialGroup()
                        .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPMostrar4Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPMostrar4Layout.createSequentialGroup()
                                        .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPMostrar4Layout.createSequentialGroup()
                                        .addComponent(jCNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPMostrar4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMostrar4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPMostrar4Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jBvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jBactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(89, 89, 89)
                        .addComponent(jBregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMostrar4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPMostrar4Layout.setVerticalGroup(
            jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMostrar4Layout.createSequentialGroup()
                .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMostrar4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMostrar4Layout.createSequentialGroup()
                        .addContainerGap(359, Short.MAX_VALUE)
                        .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMostrar4Layout.createSequentialGroup()
                        .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jCNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMostrar4Layout.createSequentialGroup()
                        .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)))
                .addGroup(jPMostrar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBactualizar)
                    .addComponent(jBvolver)
                    .addComponent(jBregistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76))
        );

        jPanel1.add(jPMostrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverActionPerformed
        // TODO add your handling code here:
        Inicio.instanciaInicio.setVisible(true);  // ← volver al Inicio REAL
        this.dispose();    
    }//GEN-LAST:event_jBvolverActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
       int fila = jTinve.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila");
        return;
    }

    int id = Integer.parseInt(modelo.getValueAt(fila, 0).toString());

    try {
        PreparedStatement ps = con.prepareStatement("DELETE FROM inventario WHERE id=?");
        ps.setInt(1, id);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Eliminado correctamente.");
        cargarInventario();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
    }
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarActionPerformed
        // TODO add your handling code here:
      try {
        PreparedStatement ps = con.prepareStatement(
            "UPDATE inventario SET nombre=?, categoria=?, cantidad=?, precio=? WHERE id=?"
        );

        ps.setString(1, jCNombre.getSelectedItem().toString());
        ps.setString(2, jTcategoria.getText());
        ps.setInt(3, Integer.parseInt(jTcantidad.getText()));
        ps.setDouble(4, Double.parseDouble(jTprecio.getText()));
        ps.setInt(5, Integer.parseInt(jTid.getText()));

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Actualizado correctamente.");
        cargarInventario();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
    }
    }//GEN-LAST:event_jBactualizarActionPerformed

    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed
        // TODO add your handling code here:
try {
        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO inventario (id, nombre, categoria, cantidad, precio) VALUES (?, ?, ?, ?, ?)"
        );

        ps.setInt(1, Integer.parseInt(jTid.getText()));
        ps.setString(2, jCNombre.getSelectedItem().toString());
        ps.setString(3, jTcategoria.getText());
        ps.setInt(4, Integer.parseInt(jTcantidad.getText()));
        ps.setDouble(5, Double.parseDouble(jTprecio.getText()));

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Registrado correctamente.");
        cargarInventario();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage());
    }
    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jTbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscarKeyReleased
        // TODO add your handling code here:
            DefaultTableModel modeloBuscar = (DefaultTableModel) jTinve.getModel();
            TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(modeloBuscar);
             jTinve.setRowSorter(trs);
            trs.setRowFilter(RowFilter.regexFilter(jTbuscar.getText()));
    }//GEN-LAST:event_jTbuscarKeyReleased

    private void jTinveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTinveMouseClicked
        // TODO add your handling code here:
           int fila = jTinve.getSelectedRow();
    
    jTid.setText(modelo.getValueAt(fila, 0).toString());
    jCNombre.setSelectedItem(modelo.getValueAt(fila, 1).toString());
    jTcategoria.setText(modelo.getValueAt(fila, 2).toString());
    jTcantidad.setText(modelo.getValueAt(fila, 3).toString());
    jTprecio.setText(modelo.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_jTinveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBactualizar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBregistrar;
    private javax.swing.JButton jBvolver;
    private javax.swing.JComboBox<String> jCNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPMostrar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTbuscar;
    private javax.swing.JTextField jTcantidad;
    private javax.swing.JTextField jTcategoria;
    private javax.swing.JTextField jTid;
    private javax.swing.JTable jTinve;
    private javax.swing.JTextField jTprecio;
    // End of variables declaration//GEN-END:variables
private void cargarInventario() {
    modelo.setRowCount(0);
    try {
        PreparedStatement ps = con.prepareStatement("SELECT * FROM inventario");
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("nombre"),
                rs.getString("categoria"),
                rs.getInt("cantidad"),
                rs.getDouble("precio")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar: " + e.getMessage());
    }
}

}
