/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import conexion.Conexion;
 
/**
 *
 * @author abrah
 */
public class Salida extends javax.swing.JFrame {
    private Connection con; // <-- conexión a la base de datos

    /**
     * Creates new form Salida
     */
    public Salida() { 
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    // Inicializamos la conexión
    con = Conexion.getConnection();
    if (con == null) {
        JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Asignamos el ActionListener al botón
    jBguardar.addActionListener(evt -> guardarSalida());    }
         
        
    {
                }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBvolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTproducto = new javax.swing.JTextField();
        jTcuandosale = new javax.swing.JTextField();
        jTfecha = new javax.swing.JTextField();
        jCregsitro = new javax.swing.JComboBox<>();
        jBguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel1.setText("Registrar productos vendidos o retirados.");

        jBvolver.setBackground(new java.awt.Color(51, 153, 255));
        jBvolver.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jBvolver.setText("Salida");
        jBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverActionPerformed(evt);
            }
        });

        jLabel2.setText("ID producto");

        jLabel3.setText("Cantidad que sale");

        jLabel4.setText("Fecha");

        jLabel5.setText("Usuario que registró");

        jCregsitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jose Antonio Rojas de la Fuente", "Marcos de la Piedra de Bonnie", "Maria Antonieta de las Nieves", "Roxana de los Angeles Cantoral" }));

        jBguardar.setBackground(new java.awt.Color(51, 153, 255));
        jBguardar.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTfecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                        .addComponent(jTcuandosale, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTproducto, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jCregsitro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(203, 203, 203))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jBvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTcuandosale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCregsitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBvolver)
                    .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverActionPerformed
          // TODO add your handling code here:
          Inicio inicio = new Inicio();
    inicio.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBvolverActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
   String id = jTproducto.getText().trim();
    String cantidad = jTcuandosale.getText().trim();
    String fecha = jTfecha.getText().trim();
    String usuario = jCregsitro.getSelectedItem().toString();

    if (id.isEmpty() || cantidad.isEmpty() || fecha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int cantidadInt = Integer.parseInt(cantidad);

        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO salida (id, cantidad, fecha, usuario) VALUES (?, ?, ?, ?)"
        );
        ps.setInt(1, Integer.parseInt(id));
        ps.setInt(2, cantidadInt);
        ps.setString(3, fecha); // o java.sql.Date si quieres tipo DATE
        ps.setString(4, usuario);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Registro guardado correctamente.");

        // Limpiar campos
        jTproducto.setText("");
        jTcuandosale.setText("");
        jTfecha.setText("");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID y cantidad deben ser números", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_jBguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBvolver;
    private javax.swing.JComboBox<String> jCregsitro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTcuandosale;
    private javax.swing.JTextField jTfecha;
    private javax.swing.JTextField jTproducto;
    // End of variables declaration//GEN-END:variables
private void guardarSalida() {
    // Capturar datos del formulario
    String productoId = jTproducto.getText().trim();
    String cantidad = jTcuandosale.getText().trim();
    String fecha = jTfecha.getText().trim();
    String usuario = jCregsitro.getSelectedItem().toString();

    // Validar campos vacíos
    if (productoId.isEmpty() || cantidad.isEmpty() || fecha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Convertir ID y cantidad a enteros
        int productoIdInt = Integer.parseInt(productoId);
        int cantidadInt = Integer.parseInt(cantidad);

        // Preparar sentencia SQL con los nombres correctos de columnas
        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO salida (producto_id, cantidad, fecha, usuario) VALUES (?, ?, ?, ?)"
        );
        ps.setInt(1, productoIdInt);
        ps.setInt(2, cantidadInt);
        ps.setString(3, fecha); // si la columna es DATE en MySQL, usar java.sql.Date.valueOf(fecha)
        ps.setString(4, usuario);

        // Ejecutar inserción
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Registro guardado correctamente.");

        // Limpiar campos
        jTproducto.setText("");
        jTcuandosale.setText("");
        jTfecha.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID y cantidad deben ser números", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

  }

